<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Setting;
use Illuminate\Support\Facades\DB;

class ComprehensiveSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Clear existing settings
        Setting::withTrashed()->forceDelete();

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $settings = [
            // General Settings
            [
                'key' => 'site_name',
                'name' => 'Site Name',
                'description' => 'The name of your website or application',
                'value' => 'SoftDev',
                'type' => 'text',
                'group' => 'general',
                'sort_order' => 1,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'site_description',
                'name' => 'Site Description',
                'description' => 'A brief description of your website',
                'value' => 'SoftDev is a software development company.',
                'type' => 'textarea',
                'group' => 'general',
                'sort_order' => 2,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'contact_email',
                'name' => 'Contact Email',
                'description' => 'Primary contact email address',
                'value' => 'support@softdev.in',
                'type' => 'email',
                'group' => 'general',
                'sort_order' => 4,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'timezone',
                'name' => 'Default Timezone',
                'description' => 'Default timezone for the application',
                'value' => 'UTC',
                'type' => 'select',
                'options' => getTimezoneOptions(),
                'group' => 'general',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'default_date_format',
                'name' => 'Default Date Format',
                'description' => 'Default format for displaying dates throughout the application',
                'value' => 'M d, Y',
                'type' => 'select',
                'options' => get_date_format_options(),
                'group' => 'general',
                'sort_order' => 6,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'default_datetime_format',
                'name' => 'Default DateTime Format',
                'description' => 'Default format for displaying date and time throughout the application',
                'value' => 'M d, Y g:i A',
                'type' => 'select',
                'options' => get_datetime_format_options(),
                'group' => 'general',
                'sort_order' => 7,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'app_url',
                'name' => 'Application URL',
                'description' => 'The base URL of your application',
                'value' => env('APP_URL', 'https://softdev.in'),
                'type' => 'url',
                'group' => 'general',
                'sort_order' => 8,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'site_favicon',
                'name' => 'Site Favicon',
                'description' => 'Favicon for the website (ICO format recommended)',
                'value' => 'build/images/favicon.ico',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 9,
                'is_public' => true,
                'is_active' => true,
            ],

            // Admin Logo Settings
            [
                'key' => 'admin_logo_small_light',
                'name' => 'Admin Small Logo (Light)',
                'description' => 'Small logo for admin panel light theme',
                'value' => 'build/images/logo-mini-dark.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 10,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'admin_logo_small_dark',
                'name' => 'Admin Small Logo (Dark)',
                'description' => 'Small logo for admin panel dark theme',
                'value' => 'build/images/logo-mini-light.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 11,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'admin_logo_light',
                'name' => 'Admin Logo (Light)',
                'description' => 'Main logo for admin panel light theme',
                'value' => 'build/images/logo-dark.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 12,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'admin_logo_dark',
                'name' => 'Admin Logo (Dark)',
                'description' => 'Main logo for admin panel dark theme',
                'value' => 'build/images/logo-light.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 13,
                'is_public' => false,
                'is_active' => true,
            ],

            // Frontend Logo Settings
            [
                'key' => 'frontend_logo_small_light',
                'name' => 'Frontend Small Logo (Light)',
                'description' => 'Small logo for frontend light theme',
                'value' => 'build/images/logo-mini-dark.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 14,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'frontend_logo_small_dark',
                'name' => 'Frontend Small Logo (Dark)',
                'description' => 'Small logo for frontend dark theme',
                'value' => 'build/images/logo-mini-light.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 15,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'frontend_logo_light',
                'name' => 'Frontend Logo (Light)',
                'description' => 'Main logo for frontend light theme',
                'value' => 'build/images/logo-dark.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 16,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'frontend_logo_dark',
                'name' => 'Frontend Logo (Dark)',
                'description' => 'Main logo for frontend dark theme',
                'value' => 'build/images/logo-light.png',
                'type' => 'file',
                'group' => 'general',
                'sort_order' => 17,
                'is_public' => true,
                'is_active' => true,
            ],

            // SMTP Settings
            [
                'key' => 'email_enabled',
                'name' => 'Enable Email System',
                'description' => 'Enable or disable email sending system-wide. When disabled, no emails will be sent.',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'smtp',
                'sort_order' => 0,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'mail_from_name',
                'name' => 'Mail From Name',
                'description' => 'Default sender name for emails',
                'value' => 'SoftDev',
                'type' => 'text',
                'group' => 'smtp',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'mail_from_address',
                'name' => 'Mail From Address',
                'description' => 'Default sender email address',
                'value' => 'support@softdev.in',
                'type' => 'email',
                'group' => 'smtp',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'mail_reply_to',
                'name' => 'Mail Reply To',
                'description' => 'Default reply-to email address',
                'value' => 'support@softdev.in',
                'type' => 'email',
                'group' => 'smtp',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'mail_driver',
                'name' => 'Mail Driver',
                'description' => 'Mail driver to use for sending emails',
                'value' => 'smtp',
                'type' => 'select',
                'options' => get_mail_driver_options(),
                'group' => 'smtp',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_host',
                'name' => 'SMTP Host',
                'description' => 'SMTP server hostname (e.g., smtp.gmail.com, smtp.outlook.com)',
                'value' => 'smtp.hostinger.com',
                'type' => 'text',
                'group' => 'smtp',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_port',
                'name' => 'SMTP Port',
                'description' => 'SMTP server port number (587 for TLS, 465 for SSL, 25 for unencrypted)',
                'value' => '465',
                'type' => 'number',
                'group' => 'smtp',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_encryption',
                'name' => 'SMTP Encryption',
                'description' => 'SMTP encryption method (TLS is recommended for security)',
                'value' => 'ssl',
                'type' => 'select',
                'options' => get_smtp_encryption_options(),
                'group' => 'smtp',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_username',
                'name' => 'SMTP Username',
                'description' => 'SMTP authentication username (usually your full email address)',
                'value' => 'support@softdev.in',
                'type' => 'text',
                'group' => 'smtp',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_password',
                'name' => 'SMTP Password',
                'description' => 'SMTP authentication password (use app-specific password for Gmail/Outlook)',
                'value' => 'hgucpkfobesincpm',
                'type' => 'password',
                'group' => 'smtp',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_ssl_mode',
                'name' => 'Enable SSL Verification',
                'description' => 'Enable SSL certificate verification (recommended for production, disable for development/testing)',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'smtp',
                'sort_order' => 6,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_timeout',
                'name' => 'Connection Timeout',
                'description' => 'SMTP connection timeout in seconds (30-60 seconds recommended)',
                'value' => '30',
                'type' => 'number',
                'group' => 'smtp',
                'sort_order' => 7,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'email_queue_enabled',
                'name' => 'Enable Email Queue',
                'description' => 'Queue emails for background sending',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'smtp',
                'sort_order' => 8,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'email_retry_attempts',
                'name' => 'Email Retry Attempts',
                'description' => 'Number of times to retry failed emails',
                'value' => '3',
                'type' => 'number',
                'group' => 'smtp',
                'sort_order' => 9,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_local_domain',
                'name' => 'SMTP Local Domain',
                'description' => 'Local domain for EHLO command',
                'value' => '',
                'type' => 'text',
                'group' => 'smtp',
                'sort_order' => 10,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'smtp_verify_peer',
                'name' => 'Verify Peer',
                'description' => 'Enable SSL peer verification (Same as SSL Mode)',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'smtp',
                'sort_order' => 11,
                'is_public' => false,
                'is_active' => true,
            ],

            // Storage Settings
            [
                'key' => 'storage_driver',
                'name' => 'Storage Driver',
                'description' => 'Default storage driver for file uploads',
                'value' => 'local',
                'type' => 'select',
                'options' => get_storage_driver_options(),
                'group' => 'storage',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'asset_url',
                'name' => 'Asset URL',
                'description' => 'Base URL for serving static assets',
                'value' => env('ASSET_URL', ''),
                'type' => 'url',
                'group' => 'storage',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'upload_path',
                'name' => 'Upload Path',
                'description' => 'Default path for file uploads',
                'value' => 'uploads',
                'type' => 'text',
                'group' => 'storage',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'max_upload_size',
                'name' => 'Max Upload Size',
                'description' => 'Maximum file upload size in MB',
                'value' => '10',
                'type' => 'number',
                'group' => 'storage',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'allowed_file_types',
                'name' => 'Allowed File Types',
                'description' => 'Comma-separated list of allowed file extensions',
                'value' => 'jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx',
                'type' => 'text',
                'group' => 'storage',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'storage_public_url',
                'name' => 'Storage Public URL',
                'description' => 'Public URL for accessing stored files',
                'value' => '/storage',
                'type' => 'text',
                'group' => 'storage',
                'sort_order' => 6,
                'is_public' => false,
                'is_active' => true,
            ],

            // Security Settings
            [
                'key' => 'session_timeout',
                'name' => 'Session Timeout',
                'description' => 'Session timeout in minutes',
                'value' => '1440',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'max_login_attempts',
                'name' => 'Max Login Attempts',
                'description' => 'Maximum failed login attempts before lockout',
                'value' => '5',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'lockout_duration',
                'name' => 'Lockout Duration',
                'description' => 'Account lockout duration in minutes',
                'value' => '15',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'two_factor_auth',
                'name' => 'Two Factor Authentication',
                'description' => 'Enable two-factor authentication',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'security',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'password_min_length',
                'name' => 'Minimum Password Length',
                'description' => 'Minimum required password length',
                'value' => '8',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'csrf_token_lifetime',
                'name' => 'CSRF Token Lifetime',
                'description' => 'CSRF token lifetime in minutes',
                'value' => '1440',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 6,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'password_reset_expiry',
                'name' => 'Password Reset Expiry',
                'description' => 'Password reset token expiry in minutes',
                'value' => '60',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 7,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'force_password_change',
                'name' => 'Force Password Change',
                'description' => 'Force users to change password after specified days (0 = disabled)',
                'value' => '0',
                'type' => 'number',
                'group' => 'security',
                'sort_order' => 9,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'login_ip_restriction',
                'name' => 'Login IP Restriction',
                'description' => 'Restrict login to specific IP addresses (comma separated)',
                'value' => '',
                'type' => 'textarea',
                'group' => 'security',
                'sort_order' => 10,
                'is_public' => false,
                'is_active' => true,
            ],

            // Appearance Settings
            [
                'key' => 'primary_color',
                'name' => 'Primary Color',
                'description' => 'Primary color for the application',
                'value' => '#245dac',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 1,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'secondary_color',
                'name' => 'Secondary Color',
                'description' => 'Secondary color for UI elements',
                'value' => '#6c757d',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 2,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'success_color',
                'name' => 'Success Color',
                'description' => 'Color for success messages and elements',
                'value' => '#198754',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 3,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'danger_color',
                'name' => 'Danger Color',
                'description' => 'Color for error messages and elements',
                'value' => '#dc3545',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 4,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'warning_color',
                'name' => 'Warning Color',
                'description' => 'Color for warning messages and elements',
                'value' => '#ffc107',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 5,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'info_color',
                'name' => 'Info Color',
                'description' => 'Color for info messages and elements',
                'value' => '#0dcaf0',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 6,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'light_color',
                'name' => 'Light Color',
                'description' => 'Light color for backgrounds and elements',
                'value' => '#e9ecef',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 7,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'dark_color',
                'name' => 'Dark Color',
                'description' => 'Dark color for text and elements',
                'value' => '#212529',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 8,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'font_family',
                'name' => 'Font Family',
                'description' => 'Default font family for the application',
                'value' => 'Roboto, sans-serif',
                'type' => 'text',
                'group' => 'appearance',
                'sort_order' => 9,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'admin_items_per_page',
                'name' => 'Admin Items Per Page',
                'description' => 'Number of items to show per page in admin tables',
                'value' => '25',
                'type' => 'select',
                'options' => get_items_per_page_options(),
                'group' => 'appearance',
                'sort_order' => 10,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'admin_primary_color',
                'name' => 'Admin Theme Color',
                'description' => 'Theme color for admin panel',
                'value' => '#245dac',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 11,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'admin_default_theme',
                'name' => 'Admin Default Theme',
                'description' => 'Default theme for admin panel',
                'value' => 'light',
                'type' => 'select',
                'options' => get_theme_options(),
                'group' => 'appearance',
                'sort_order' => 14,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'frontend_default_theme',
                'name' => 'Frontend Default Theme',
                'description' => 'Default theme for frontend',
                'value' => 'light',
                'type' => 'select',
                'options' => get_theme_options(),
                'group' => 'appearance',
                'sort_order' => 15,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'front_items_per_page',
                'name' => 'Frontend Items Per Page',
                'description' => 'Number of items to show per page in frontend lists',
                'value' => '10',
                'type' => 'number',
                'group' => 'appearance',
                'sort_order' => 16,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'front_primary_color',
                'name' => 'Frontend Primary Color',
                'description' => 'Primary color for frontend theme',
                'value' => '#245dac',
                'type' => 'color',
                'group' => 'appearance',
                'sort_order' => 17,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'front_show_breadcrumbs',
                'name' => 'Show Breadcrumbs',
                'description' => 'Show breadcrumbs on frontend pages',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'appearance',
                'sort_order' => 18,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'front_enable_search',
                'name' => 'Enable Search',
                'description' => 'Enable search functionality on frontend',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'appearance',
                'sort_order' => 19,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'front_show_sidebar',
                'name' => 'Show Sidebar',
                'description' => 'Show sidebar on frontend pages',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'appearance',
                'sort_order' => 20,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'front_enable_comments',
                'name' => 'Enable Comments',
                'description' => 'Enable comments on frontend posts',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'appearance',
                'sort_order' => 21,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'items_per_page',
                'name' => 'Items Per Page (Legacy)',
                'description' => 'Legacy items per page setting',
                'value' => '10',
                'type' => 'number',
                'group' => 'appearance',
                'sort_order' => 22,
                'is_public' => true,
                'is_active' => true,
            ],

            // System Settings
            [
                'key' => 'app_debug',
                'name' => 'Debug Mode',
                'description' => 'Enable debug mode for development',
                'value' => env('APP_DEBUG', false) ? '1' : '0',
                'type' => 'boolean',
                'group' => 'system',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'app_env',
                'name' => 'Environment',
                'description' => 'Application environment',
                'value' => env('APP_ENV', 'production'),
                'type' => 'select',
                'options' => [
                    'production' => 'Production',
                    'staging' => 'Staging',
                    'development' => 'Development',
                    'local' => 'Local',
                ],
                'group' => 'system',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'cache_enabled',
                'name' => 'Cache Enabled',
                'description' => 'Enable application caching',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'system',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'log_level',
                'name' => 'Log Level',
                'description' => 'Application logging level',
                'value' => 'error',
                'type' => 'select',
                'options' => [
                    'emergency' => 'Emergency',
                    'alert' => 'Alert',
                    'critical' => 'Critical',
                    'error' => 'Error',
                    'warning' => 'Warning',
                    'notice' => 'Notice',
                    'info' => 'Info',
                    'debug' => 'Debug',
                ],
                'group' => 'system',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'maintenance_mode',
                'name' => 'Maintenance Mode',
                'description' => 'Enable maintenance mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'system',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'maintenance_message',
                'name' => 'Maintenance Message',
                'description' => 'Message to display during maintenance',
                'value' => 'We are currently performing scheduled maintenance. Please check back soon.',
                'type' => 'textarea',
                'group' => 'system',
                'sort_order' => 6,
                'is_public' => true,
                'is_active' => true,
            ],

            // Notification Settings
            [
                'key' => 'notifications_enabled',
                'name' => 'Notifications Enabled',
                'description' => 'Enable system notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'notifications',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'email_notifications',
                'name' => 'Email Notifications',
                'description' => 'Send notifications via email',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'notifications',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'admin_notification_email',
                'name' => 'Admin Notification Email',
                'description' => 'Email address for admin notifications',
                'value' => 'kalpeshmeniya96@gmail.com',
                'type' => 'email',
                'group' => 'notifications',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'notification_frequency',
                'name' => 'Notification Frequency',
                'description' => 'How often to send digest notifications',
                'value' => 'daily',
                'type' => 'select',
                'options' => [
                    'immediate' => 'Immediate',
                    'hourly' => 'Hourly',
                    'daily' => 'Daily',
                    'weekly' => 'Weekly',
                ],
                'group' => 'notifications',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],

            // Google Authentication Settings
            [
                'key' => 'google_auth_enabled',
                'name' => 'Enable Google Authentication',
                'description' => 'Allow users to login/register using their Google account',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'authentication',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'google_client_id',
                'name' => 'Google Client ID',
                'description' => 'Google OAuth Client ID from Google Cloud Console',
                'value' => '',
                'type' => 'text',
                'group' => 'authentication',
                'sort_order' => 2,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'google_client_secret',
                'name' => 'Google Client Secret',
                'description' => 'Google OAuth Client Secret from Google Cloud Console',
                'value' => '',
                'type' => 'text',
                'group' => 'authentication',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],

            // API Settings
            [
                'key' => 'api_enabled',
                'name' => 'API Enabled',
                'description' => 'Enable API access',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'api',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'api_guest_rate_limit',
                'name' => 'API Guest Rate Limit',
                'description' => 'Maximum API requests per day for guest users (without authentication)',
                'value' => '100',
                'type' => 'number',
                'group' => 'api',
                'sort_order' => 3,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'api_user_rate_limit',
                'name' => 'API User Rate Limit',
                'description' => 'Maximum API requests per day for authenticated users (with API token)',
                'value' => '1000',
                'type' => 'number',
                'group' => 'api',
                'sort_order' => 4,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'api_version',
                'name' => 'API Version',
                'description' => 'Current API version',
                'value' => 'v1',
                'type' => 'select',
                'options' => [
                    'v1' => 'Version 1',
                    'v2' => 'Version 2',
                ],
                'group' => 'api',
                'sort_order' => 4,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'ip_api_url',
                'name' => 'IP API URL',
                'description' => 'URL for IP Geolocation service (e.g. https://ip-api.in/api/v1/ip/)',
                'value' => 'https://ip-api.in/api/v1/ip/',
                'type' => 'text',
                'group' => 'api',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'ip_api_token',
                'name' => 'IP API Token',
                'description' => 'Bearer token for IP API service',
                'value' => '',
                'type' => 'password',
                'group' => 'api',
                'sort_order' => 6,
                'is_public' => false,
                'is_active' => true,
            ],

            // Mobile Application Settings
            [
                'key' => 'mobile_app_name',
                'name' => 'Mobile App Name',
                'description' => 'Name of the mobile application',
                'value' => env('APP_NAME', 'SOFTDEV'),
                'type' => 'text',
                'group' => 'mobile_app',
                'sort_order' => 1,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_default_theme',
                'name' => 'Mobile Default Theme',
                'description' => 'Default theme for the mobile app',
                'value' => 'light',
                'type' => 'select',
                'options' => get_theme_options(),
                'group' => 'mobile_app',
                'sort_order' => 2,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'android_application_token',
                'name' => 'Android Application Token',
                'description' => 'Application token for the Android application',
                'value' => 'com.geniuspolicy.app',
                'type' => 'text',
                'group' => 'mobile_app',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'ios_application_token',
                'name' => 'iOS Application Token',
                'description' => 'Application token for the iOS application',
                'value' => 'com.geniuspolicy.app',
                'type' => 'text',
                'group' => 'mobile_app',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_app_version',
                'name' => 'Mobile App Version',
                'description' => 'Current version of the mobile application',
                'value' => '1.0.0',
                'type' => 'text',
                'group' => 'mobile_app',
                'sort_order' => 5,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_min_version',
                'name' => 'Minimum Supported Version',
                'description' => 'Minimum supported version for the mobile application',
                'value' => '1.0.0',
                'type' => 'text',
                'group' => 'mobile_app',
                'sort_order' => 6,
                'is_public' => true,
                'is_active' => true,
            ],

            [
                'key' => 'mobile_app_link_android',
                'name' => 'Android App Link',
                'description' => 'Play Store link for the Android application',
                'value' => '',
                'type' => 'url',
                'group' => 'mobile_app',
                'sort_order' => 7,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_app_link_ios',
                'name' => 'iOS App Link',
                'description' => 'App Store link for the iOS application',
                'value' => '',
                'type' => 'url',
                'group' => 'mobile_app',
                'sort_order' => 8,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_maintenance_mode',
                'name' => 'Mobile Maintenance Mode',
                'description' => 'Enable maintenance mode for mobile app',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'mobile_app',
                'sort_order' => 9,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_force_update',
                'name' => 'Force Update',
                'description' => 'Force users to update the mobile application',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'mobile_app',
                'sort_order' => 10,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_maintenance_message',
                'name' => 'Maintenance Message',
                'description' => 'Message shown to users when the mobile app is temporarily unavailable due to scheduled or unscheduled maintenance.',
                'value' => 'We’re performing a brief system maintenance to improve your experience. The app will be back shortly. Thank you for your patience.',
                'type' => 'textarea',
                'group' => 'mobile_app',
                'sort_order' => 11,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_update_message',
                'name' => 'Update Message',
                'description' => 'Message shown to users when a new app version is available and an update is required or recommended.',
                'value' => 'A new version of the app is available with improved performance and bug fixes. Please update the app to continue using all features.',
                'type' => 'textarea',
                'group' => 'mobile_app',
                'sort_order' => 12,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_privacy_policy_url',
                'name' => 'Mobile Privacy Policy URL',
                'description' => 'URL for the mobile app privacy policy',
                'value' => '',
                'type' => 'url',
                'group' => 'mobile_app',
                'sort_order' => 13,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_terms_url',
                'name' => 'Mobile Terms URL',
                'description' => 'URL for the mobile app terms of service',
                'value' => '',
                'type' => 'url',
                'group' => 'mobile_app',
                'sort_order' => 14,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_splash_logo_light',
                'name' => 'Mobile Splash Logo (Light)',
                'description' => 'Logo displayed on the mobile app splash screen (Light theme)',
                'value' => 'build/images/logo-mini-dark.png',
                'type' => 'file',
                'group' => 'mobile_app',
                'sort_order' => 15,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_splash_logo_dark',
                'name' => 'Mobile Splash Logo (Dark)',
                'description' => 'Logo displayed on the mobile app splash screen (Dark theme)',
                'value' => 'build/images/logo-mini-light.png',
                'type' => 'file',
                'group' => 'mobile_app',
                'sort_order' => 16,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_home_logo_light',
                'name' => 'Mobile Home Logo (Light)',
                'description' => 'Logo displayed on the mobile app home screen (Light theme)',
                'value' => 'build/images/logo-dark.png',
                'type' => 'file',
                'group' => 'mobile_app',
                'sort_order' => 17,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_home_logo_dark',
                'name' => 'Mobile Home Logo (Dark)',
                'description' => 'Logo displayed on the mobile app home screen (Dark theme)',
                'value' => 'build/images/logo-light.png',
                'type' => 'file',
                'group' => 'mobile_app',
                'sort_order' => 18,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_announcement_show',
                'name' => 'Show Mobile Announcement',
                'description' => 'Display announcement banner in the mobile app',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'mobile_app',
                'sort_order' => 19,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_announcement_dismissable',
                'name' => 'Announcement Dismissable',
                'description' => 'Allow users to dismiss the announcement banner',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'mobile_app',
                'sort_order' => 20,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_announcement_content',
                'name' => 'Mobile Announcement Content',
                'description' => 'Content to display in the mobile app announcement banner (supports HTML)',
                'value' => '<p>Welcome to our mobile app! Check out our latest updates.</p>',
                'type' => 'html',
                'group' => 'mobile_app',
                'sort_order' => 21,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_help_support_link',
                'name' => 'Mobile Help & Support Link',
                'description' => 'Link for help and support in the mobile app',
                'value' => '',
                'type' => 'url',
                'group' => 'mobile_app',
                'sort_order' => 22,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'mobile_rate_app_link',
                'name' => 'Mobile Rate App Link',
                'description' => 'Link to rate the mobile application',
                'value' => '',
                'type' => 'url',
                'group' => 'mobile_app',
                'sort_order' => 23,
                'is_public' => true,
                'is_active' => true,
            ],
            // [
            //     'key' => 'mobile_google_auth_enabled',
            //     'name' => 'Enable Google Authentication (Mobile)',
            //     'description' => 'Allow mobile app users to login/register using their Google account',
            //     'value' => '1',
            //     'type' => 'boolean',
            //     'group' => 'mobile_app',
            //     'sort_order' => 24,
            //     'is_public' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'key' => 'mobile_google_client_id',
            //     'name' => 'Google Client ID (Mobile)',
            //     'description' => 'Google OAuth Client ID for mobile app from Google Cloud Console',
            //     'value' => '',
            //     'type' => 'text',
            //     'group' => 'mobile_app',
            //     'sort_order' => 25,
            //     'is_public' => true,
            //     'is_active' => true,
            // ],
            // [
            //     'key' => 'mobile_google_client_secret',
            //     'name' => 'Google Client Secret (Mobile)',
            //     'description' => 'Google OAuth Client Secret for mobile app from Google Cloud Console',
            //     'value' => '',
            //     'type' => 'text',
            //     'group' => 'mobile_app',
            //     'sort_order' => 26,
            //     'is_public' => true,
            //     'is_active' => true,
            // ],

            // Socket.IO Settings
            [
                'key' => 'socket_enabled',
                'name' => 'Enable Socket.IO',
                'description' => 'Enable real-time features using Socket.IO',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'socket',
                'sort_order' => 1,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'socket_server_url',
                'name' => 'Socket Server URL',
                'description' => 'URL of the Socket.IO server (e.g., http://localhost:3000)',
                'value' => env('SOCKET_SERVER_URL', 'http://localhost:3000'),
                'type' => 'url',
                'group' => 'socket',
                'sort_order' => 2,
                'is_public' => true,
                'is_active' => true,
            ],
            [
                'key' => 'socket_server_port',
                'name' => 'Socket Server Port',
                'description' => 'Port number for the Socket.IO server',
                'value' => env('SOCKET_SERVER_PORT', '3000'),
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 3,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'socket_reconnection_attempts',
                'name' => 'Reconnection Attempts',
                'description' => 'Number of reconnection attempts before giving up',
                'value' => '3',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 4,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'socket_reconnection_delay',
                'name' => 'Reconnection Delay (ms)',
                'description' => 'Delay between reconnection attempts in milliseconds',
                'value' => '5000',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 5,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'socket_reconnection_delay_max',
                'name' => 'Max Reconnection Delay (ms)',
                'description' => 'Maximum delay between reconnection attempts in milliseconds',
                'value' => '10000',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 6,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'socket_heartbeat_interval',
                'name' => 'Heartbeat Interval (ms)',
                'description' => 'Interval for sending heartbeat signals in milliseconds',
                'value' => '30000',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 7,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'socket_timeout',
                'name' => 'Connection Timeout (ms)',
                'description' => 'Timeout for socket connection in milliseconds',
                'value' => '10000',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 8,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'analytics_store_pageview',
                'name' => 'Store Pageviews',
                'description' => 'Whether to store pageview data in the database for analytics',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'socket',
                'sort_order' => 9,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'analytics_deduplication_time',
                'name' => 'Pageview Deduplication Time (s)',
                'description' => 'Seconds to wait before recording another pageview from the same user for the same page',
                'value' => '30',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 10,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'analytics_retention_days',
                'name' => 'Analytics Retention Days',
                'description' => 'Number of days to keep pageview data (0 = keep forever)',
                'value' => '0',
                'type' => 'number',
                'group' => 'socket',
                'sort_order' => 11,
                'is_public' => false,
                'is_active' => true,
            ],
            [
                'key' => 'analytics_exclude_ips',
                'name' => 'Exclude IP Addresses',
                'description' => 'Comma-separated list of IP addresses to exclude from analytics',
                'value' => '',
                'type' => 'textarea',
                'group' => 'socket',
                'sort_order' => 12,
                'is_public' => false,
                'is_active' => true,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
